# Generated by Django 4.2 on 2023-05-05 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='count',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='primecost',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='cost',
            field=models.FloatField(blank=True),
        ),
    ]
