# Generated by Django 4.2 on 2023-05-05 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_component_count_alter_component_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='components',
            field=models.ManyToManyField(null=True, to='core.component'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='primecost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tools',
            field=models.ManyToManyField(null=True, to='core.tool'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='usage',
            field=models.IntegerField(null=True),
        ),
    ]
