# Generated by Django 4.2 on 2023-05-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_component_count_alter_component_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='depreciation',
            field=models.FloatField(null=True),
        ),
    ]
