# Generated by Django 4.2 on 2023-05-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tool_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='unit',
            field=models.CharField(max_length=50, null=True, verbose_name='Единица измрения'),
        ),
    ]
