# Generated by Django 4.2 on 2023-05-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_component_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='cost',
            field=models.FloatField(null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='component',
            name='count',
            field=models.FloatField(null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='component',
            name='price',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Выход'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='primecost',
            field=models.FloatField(null=True, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='cost',
            field=models.FloatField(null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='depreciation',
            field=models.FloatField(null=True, verbose_name='Амортизация'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='time',
            field=models.IntegerField(null=True, verbose_name='Время применения'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='usage',
            field=models.IntegerField(null=True, verbose_name='Срок использования'),
        ),
    ]
