# Generated by Django 4.2 on 2023-05-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_component_cost_alter_component_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='instance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='instance',
            field=models.BooleanField(default=True),
        ),
    ]
