# Generated by Django 4.2 on 2023-05-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_component_instance_recipe_instance_tool_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='instance',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='instance',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='instance',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='component',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
