# Generated by Django 4.2 on 2023-05-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_recipe_components_alter_recipe_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='components',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipe', to='core.component', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tools',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipe', to='core.tool', verbose_name='Инструменты'),
        ),
    ]
