# Generated by Django 4.2 on 2023-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_recipe_components_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='component',
            name='count',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='component',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
