# Generated by Django 4.2 on 2023-05-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_component_cost_alter_component_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='components',
            field=models.ManyToManyField(null=True, related_name='recipe', to='core.component', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='parent_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tools',
            field=models.ManyToManyField(null=True, related_name='recipe', to='core.tool', verbose_name='Инструменты'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='time',
            field=models.IntegerField(default=0, null=True, verbose_name='Время применения'),
        ),
    ]
