# Generated by Django 4.2 on 2023-06-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_recipe_components_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='parent_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='recipe', to='core.component', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='primecost',
            field=models.FloatField(default=0, null=True, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='recipe', to='core.tool', verbose_name='Инструменты'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='parent_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
