# Generated by Django 4.2 on 2023-06-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_recipe_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ('name', 'price', 'owner'), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('name', 'owner'), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ('name', 'cost', 'owner'), 'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('name',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.DeleteModel(
            name='UserId',
        ),
    ]
